---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: web
  - port: 9113
    name: exporter
  selector:
    app: nginx
