apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  initContainers:
  - name: init
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts: [{ name: app, mountPath: /app }]
  containers:
  - name: nginx
    image: makac/homework1:nginx
    imagePullPolicy: Always
    readinessProbe:
      httpGet:
        path: /index.html
        port: 8000
    livenessProbe:
      tcpSocket: { port: 8000 }
    volumeMounts: [{ name: app, mountPath: /app }]
  volumes: [{ name: app, emptyDir: {} }]
